config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    collection do
      get :search
    end
    get 'comment', to: 'posts#new_comment'
    post 'comment', to: 'posts#create_comment'
  end
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
        belongs_to :user
        belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
        belongs_to :user
        has_many :comments, dependent: :destroy
        has_one_attached :image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show update destroy edit]
  def index
    @posts = Post.all
    @post = Post.new
  end
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      redirect_to root_path alert: 'error al crear post'
    end
  end 
  def show 
    #inserte aqui  el post a mostrar 
    @comments = @post.comments
    end 
  def edit
  end

  def update
   @post.update(post_params)
   if @post.save
    respond_to :js
   else 
      redirect_to root_path, alert: 'El post no fue actualizado'
   end 
  end
  def destroy
    @post.destroy
    respond_to :js
  end


# metodos de comment
def new_comment
  @post = Post.find(params[:post_id])
  @comment = Comment.new
  respond_to :js
end

def create_comment
  @comment = Comment.new(comment_params)
  @comment.user = current_user
  @comment.post_id = params[:post_id]
  if @comment.save
  respond_to :js
  else 
    redirect_to root_path, alert: 'comentario no se pudo crear'
 end
end


  def search
    parameters = params[:search]
    if parameters.blank?
      @posts = Post.all
      respond_to :js
    elsif parameters.nil?
      @posts = Post.all
      respond_to :js
    else
      @posts = Post.where('title LIKE ?',"%#{parameters}%")
      respond_to :js
    end

end



  private
  def post_params
    params.require(:post).permit(:title, :user_id, :image)
  end 

  def set_post
    @post = Post.find(params[:id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end 
  def comment_params
    params.require(:comment).permit(:content)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxPrePrueba</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script
      src="http://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container"><%= yield %></div>
    <script
      src="http://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"   crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/posts/_comment.html.erb
<div class="alert alert-primary" role="alert">
      <h4><%= comment.content%></h4> 
</div>

app/views/posts/_form-comment.html.erb
<%= form_with(url: post_comment_path(@post), scope: :comment) do |f| %>
        <%= f.label :Content%>
        <%= f.text_area :content %>
        <%= f.submit class: 'btn btn-success'%>

<% end %>

app/views/posts/_form.html.erb
<div class="row">
                <div class="col col-md-4">
                        <%= form_with(model: post) do |f| %>
                                <%= f.label :Title%>
                                <%= f.text_field :title, class: 'form-control' %>
                                <%= f.hidden_field :user_id, value: current_user.id %>
                                <%= f.file_field :image %>
                                <%= f.submit class: 'btn btn-success'%>
                        
                        <% end %>
        
        
                </div>

app/views/posts/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      
                    </div>
                    <div class="modal-footer">
                      
                    </div>
                  </div>
                </div>
              </div>

app/views/posts/_post.html.erb
<tr id="<%= post.id%>">
        <td><%= post.title%></td>
        <td><%= image_tag(post.image.variant(resize: '200x200')) %></td>
        <td><%= link_to  "show", post_path(post), data: {remote: true } %></td>
        <td><%= link_to  "Edit", edit_post_path(post), data:{ remote: true }%></td>
        <td><%= link_to  "Delete",post_path(post), method: :delete, data:{ remote: true } %></td>
        <td><%= link_to  "Comment", post_comment_path(post), data: { remote: true } %></td>
        <td id="contador"><span class="badge badge-success"><%= post.comments.count%></span></td>
</tr>

app/views/posts/create.js.erb
$('#tbody').append("<%= j render @post %>");
$('#post_title').val('');

app/views/posts/destroy.js.erb
alert('objeto eliminado');
$('#<%= @post.id%>').fadeOut();

app/views/posts/edit.js.erb
$('.modal-body').html("<%= j render 'form', post: @post %>");
$('#exampleModal').modal('show');

app/views/posts/index.html.erb
        <%= render  "form", post: @post  %>
        <div class="col col-md-8">
                <div class="contenedor">
                 <label for="">Buscar Post</label>
                 <input type="text" name="" id="search" class="form-control">
                <table class="table">
                                <thead>
                                        <tr>
                                        <th scope="col">Title</th>
                                        <th scope="col"></th>
                                        <th scope="col"></th>
                                        <th scope="col"></th>
                                        <th scope="col"></th>
                                        <th scope="col">Nº Commentarios</th>
                                        </tr>
                                </thead>
                                <tbody id="tbody">
                                        
                                          <%= render  @posts  %>
                                </tbody>
                                </thead>
                                </table>
                                <%= render  "modal" %>
                                
                </div>
        </div>
</div>


  <script>
                  $('#search').keyup(function(){
                    $.ajax({
                      type: "GET",
                      url: "<%= search_posts_path%>",
                      data: {search: $('#search').val()},
                      success: function (response) {

                      }
                });
                  });
                </script>

app/views/posts/new_comment.js.erb
$('#exampleModal').modal('show');
$('.modal-body').html("<%= j render 'form-comment', post: @post, comment:   @comment %>")
k

app/views/posts/search.js.erb
$('#tbody').html("<%= j render @posts %>");

app/views/posts/show.js.erb
$('#exampleModal').modal('show');
$('.modal-body').html('<%@post.comments.each do |comment|%><%= comment.content%> <a href>x</a><br><%end%>');

app/views/posts/update.js.erb
$('#<%= @post.id%>').replaceWith("<%= j render @post %>");
$("#exampleModal").modal("hide");